// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.ctodb.push.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code cn.ctodb.push.proto.ToType}
   */
  public enum ToType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 用户
     * </pre>
     *
     * <code>USER = 0;</code>
     */
    USER(0),
    /**
     * <pre>
     * 群组
     * </pre>
     *
     * <code>GROUP = 1;</code>
     */
    GROUP(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 用户
     * </pre>
     *
     * <code>USER = 0;</code>
     */
    public static final int USER_VALUE = 0;
    /**
     * <pre>
     * 群组
     * </pre>
     *
     * <code>GROUP = 1;</code>
     */
    public static final int GROUP_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ToType valueOf(int value) {
      return forNumber(value);
    }

    public static ToType forNumber(int value) {
      switch (value) {
        case 0: return USER;
        case 1: return GROUP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ToType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ToType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ToType>() {
            public ToType findValueByNumber(int number) {
              return ToType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.ctodb.push.proto.Message.getDescriptor().getEnumTypes().get(0);
    }

    private static final ToType[] VALUES = values();

    public static ToType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ToType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cn.ctodb.push.proto.ToType)
  }

  public interface BaseInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.ctodb.push.proto.BaseInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 发送者
     * </pre>
     *
     * <code>string from = 1;</code>
     */
    java.lang.String getFrom();
    /**
     * <pre>
     * 发送者
     * </pre>
     *
     * <code>string from = 1;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <pre>
     * 接受者
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    java.lang.String getTo();
    /**
     * <pre>
     * 接受者
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     * 接收者类型
     * </pre>
     *
     * <code>.cn.ctodb.push.proto.ToType toType = 3;</code>
     */
    int getToTypeValue();
    /**
     * <pre>
     * 接收者类型
     * </pre>
     *
     * <code>.cn.ctodb.push.proto.ToType toType = 3;</code>
     */
    cn.ctodb.push.proto.Message.ToType getToType();

    /**
     * <pre>
     * 时间戳用于检查重复发送
     * </pre>
     *
     * <code>int64 cc = 4;</code>
     */
    long getCc();
  }
  /**
   * Protobuf type {@code cn.ctodb.push.proto.BaseInfo}
   */
  public  static final class BaseInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.ctodb.push.proto.BaseInfo)
      BaseInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseInfo.newBuilder() to construct.
    private BaseInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseInfo() {
      from_ = "";
      to_ = "";
      toType_ = 0;
      cc_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              toType_ = rawValue;
              break;
            }
            case 32: {

              cc_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_BaseInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_BaseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ctodb.push.proto.Message.BaseInfo.class, cn.ctodb.push.proto.Message.BaseInfo.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object from_;
    /**
     * <pre>
     * 发送者
     * </pre>
     *
     * <code>string from = 1;</code>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送者
     * </pre>
     *
     * <code>string from = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 2;
    private volatile java.lang.Object to_;
    /**
     * <pre>
     * 接受者
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 接受者
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTYPE_FIELD_NUMBER = 3;
    private int toType_;
    /**
     * <pre>
     * 接收者类型
     * </pre>
     *
     * <code>.cn.ctodb.push.proto.ToType toType = 3;</code>
     */
    public int getToTypeValue() {
      return toType_;
    }
    /**
     * <pre>
     * 接收者类型
     * </pre>
     *
     * <code>.cn.ctodb.push.proto.ToType toType = 3;</code>
     */
    public cn.ctodb.push.proto.Message.ToType getToType() {
      @SuppressWarnings("deprecation")
      cn.ctodb.push.proto.Message.ToType result = cn.ctodb.push.proto.Message.ToType.valueOf(toType_);
      return result == null ? cn.ctodb.push.proto.Message.ToType.UNRECOGNIZED : result;
    }

    public static final int CC_FIELD_NUMBER = 4;
    private long cc_;
    /**
     * <pre>
     * 时间戳用于检查重复发送
     * </pre>
     *
     * <code>int64 cc = 4;</code>
     */
    public long getCc() {
      return cc_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, from_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, to_);
      }
      if (toType_ != cn.ctodb.push.proto.Message.ToType.USER.getNumber()) {
        output.writeEnum(3, toType_);
      }
      if (cc_ != 0L) {
        output.writeInt64(4, cc_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, from_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, to_);
      }
      if (toType_ != cn.ctodb.push.proto.Message.ToType.USER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, toType_);
      }
      if (cc_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, cc_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.ctodb.push.proto.Message.BaseInfo)) {
        return super.equals(obj);
      }
      cn.ctodb.push.proto.Message.BaseInfo other = (cn.ctodb.push.proto.Message.BaseInfo) obj;

      boolean result = true;
      result = result && getFrom()
          .equals(other.getFrom());
      result = result && getTo()
          .equals(other.getTo());
      result = result && toType_ == other.toType_;
      result = result && (getCc()
          == other.getCc());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + TOTYPE_FIELD_NUMBER;
      hash = (53 * hash) + toType_;
      hash = (37 * hash) + CC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCc());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.ctodb.push.proto.Message.BaseInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ctodb.push.proto.Message.BaseInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.BaseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ctodb.push.proto.Message.BaseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.BaseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ctodb.push.proto.Message.BaseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.BaseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ctodb.push.proto.Message.BaseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.BaseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.ctodb.push.proto.Message.BaseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.BaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ctodb.push.proto.Message.BaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.ctodb.push.proto.Message.BaseInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.ctodb.push.proto.BaseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.ctodb.push.proto.BaseInfo)
        cn.ctodb.push.proto.Message.BaseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_BaseInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_BaseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.ctodb.push.proto.Message.BaseInfo.class, cn.ctodb.push.proto.Message.BaseInfo.Builder.class);
      }

      // Construct using cn.ctodb.push.proto.Message.BaseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        from_ = "";

        to_ = "";

        toType_ = 0;

        cc_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_BaseInfo_descriptor;
      }

      @java.lang.Override
      public cn.ctodb.push.proto.Message.BaseInfo getDefaultInstanceForType() {
        return cn.ctodb.push.proto.Message.BaseInfo.getDefaultInstance();
      }

      @java.lang.Override
      public cn.ctodb.push.proto.Message.BaseInfo build() {
        cn.ctodb.push.proto.Message.BaseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.ctodb.push.proto.Message.BaseInfo buildPartial() {
        cn.ctodb.push.proto.Message.BaseInfo result = new cn.ctodb.push.proto.Message.BaseInfo(this);
        result.from_ = from_;
        result.to_ = to_;
        result.toType_ = toType_;
        result.cc_ = cc_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.ctodb.push.proto.Message.BaseInfo) {
          return mergeFrom((cn.ctodb.push.proto.Message.BaseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.ctodb.push.proto.Message.BaseInfo other) {
        if (other == cn.ctodb.push.proto.Message.BaseInfo.getDefaultInstance()) return this;
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (other.toType_ != 0) {
          setToTypeValue(other.getToTypeValue());
        }
        if (other.getCc() != 0L) {
          setCc(other.getCc());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.ctodb.push.proto.Message.BaseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.ctodb.push.proto.Message.BaseInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object from_ = "";
      /**
       * <pre>
       * 发送者
       * </pre>
       *
       * <code>string from = 1;</code>
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 发送者
       * </pre>
       *
       * <code>string from = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送者
       * </pre>
       *
       * <code>string from = 1;</code>
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者
       * </pre>
       *
       * <code>string from = 1;</code>
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者
       * </pre>
       *
       * <code>string from = 1;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        from_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <pre>
       * 接受者
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 接受者
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 接受者
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接受者
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接受者
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private int toType_ = 0;
      /**
       * <pre>
       * 接收者类型
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.ToType toType = 3;</code>
       */
      public int getToTypeValue() {
        return toType_;
      }
      /**
       * <pre>
       * 接收者类型
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.ToType toType = 3;</code>
       */
      public Builder setToTypeValue(int value) {
        toType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者类型
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.ToType toType = 3;</code>
       */
      public cn.ctodb.push.proto.Message.ToType getToType() {
        @SuppressWarnings("deprecation")
        cn.ctodb.push.proto.Message.ToType result = cn.ctodb.push.proto.Message.ToType.valueOf(toType_);
        return result == null ? cn.ctodb.push.proto.Message.ToType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 接收者类型
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.ToType toType = 3;</code>
       */
      public Builder setToType(cn.ctodb.push.proto.Message.ToType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        toType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者类型
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.ToType toType = 3;</code>
       */
      public Builder clearToType() {
        
        toType_ = 0;
        onChanged();
        return this;
      }

      private long cc_ ;
      /**
       * <pre>
       * 时间戳用于检查重复发送
       * </pre>
       *
       * <code>int64 cc = 4;</code>
       */
      public long getCc() {
        return cc_;
      }
      /**
       * <pre>
       * 时间戳用于检查重复发送
       * </pre>
       *
       * <code>int64 cc = 4;</code>
       */
      public Builder setCc(long value) {
        
        cc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间戳用于检查重复发送
       * </pre>
       *
       * <code>int64 cc = 4;</code>
       */
      public Builder clearCc() {
        
        cc_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.ctodb.push.proto.BaseInfo)
    }

    // @@protoc_insertion_point(class_scope:cn.ctodb.push.proto.BaseInfo)
    private static final cn.ctodb.push.proto.Message.BaseInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.ctodb.push.proto.Message.BaseInfo();
    }

    public static cn.ctodb.push.proto.Message.BaseInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseInfo>
        PARSER = new com.google.protobuf.AbstractParser<BaseInfo>() {
      @java.lang.Override
      public BaseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.ctodb.push.proto.Message.BaseInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.ctodb.push.proto.MessageResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 返回消息id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     * 与TextReq对应，用于检查发送状态
     * </pre>
     *
     * <code>int64 cc = 2;</code>
     */
    long getCc();

    /**
     * <pre>
     * 实际发送成功时间戳
     * </pre>
     *
     * <code>int64 ts = 3;</code>
     */
    long getTs();
  }
  /**
   * Protobuf type {@code cn.ctodb.push.proto.MessageResp}
   */
  public  static final class MessageResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.ctodb.push.proto.MessageResp)
      MessageRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageResp.newBuilder() to construct.
    private MessageResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageResp() {
      id_ = 0L;
      cc_ = 0L;
      ts_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              cc_ = input.readInt64();
              break;
            }
            case 24: {

              ts_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_MessageResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_MessageResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ctodb.push.proto.Message.MessageResp.class, cn.ctodb.push.proto.Message.MessageResp.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * 返回消息id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int CC_FIELD_NUMBER = 2;
    private long cc_;
    /**
     * <pre>
     * 与TextReq对应，用于检查发送状态
     * </pre>
     *
     * <code>int64 cc = 2;</code>
     */
    public long getCc() {
      return cc_;
    }

    public static final int TS_FIELD_NUMBER = 3;
    private long ts_;
    /**
     * <pre>
     * 实际发送成功时间戳
     * </pre>
     *
     * <code>int64 ts = 3;</code>
     */
    public long getTs() {
      return ts_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (cc_ != 0L) {
        output.writeInt64(2, cc_);
      }
      if (ts_ != 0L) {
        output.writeInt64(3, ts_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (cc_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, cc_);
      }
      if (ts_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, ts_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.ctodb.push.proto.Message.MessageResp)) {
        return super.equals(obj);
      }
      cn.ctodb.push.proto.Message.MessageResp other = (cn.ctodb.push.proto.Message.MessageResp) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getCc()
          == other.getCc());
      result = result && (getTs()
          == other.getTs());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCc());
      hash = (37 * hash) + TS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTs());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.ctodb.push.proto.Message.MessageResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ctodb.push.proto.Message.MessageResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.MessageResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ctodb.push.proto.Message.MessageResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.MessageResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ctodb.push.proto.Message.MessageResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.MessageResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ctodb.push.proto.Message.MessageResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.MessageResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.ctodb.push.proto.Message.MessageResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.MessageResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ctodb.push.proto.Message.MessageResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.ctodb.push.proto.Message.MessageResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.ctodb.push.proto.MessageResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.ctodb.push.proto.MessageResp)
        cn.ctodb.push.proto.Message.MessageRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_MessageResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_MessageResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.ctodb.push.proto.Message.MessageResp.class, cn.ctodb.push.proto.Message.MessageResp.Builder.class);
      }

      // Construct using cn.ctodb.push.proto.Message.MessageResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        cc_ = 0L;

        ts_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_MessageResp_descriptor;
      }

      @java.lang.Override
      public cn.ctodb.push.proto.Message.MessageResp getDefaultInstanceForType() {
        return cn.ctodb.push.proto.Message.MessageResp.getDefaultInstance();
      }

      @java.lang.Override
      public cn.ctodb.push.proto.Message.MessageResp build() {
        cn.ctodb.push.proto.Message.MessageResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.ctodb.push.proto.Message.MessageResp buildPartial() {
        cn.ctodb.push.proto.Message.MessageResp result = new cn.ctodb.push.proto.Message.MessageResp(this);
        result.id_ = id_;
        result.cc_ = cc_;
        result.ts_ = ts_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.ctodb.push.proto.Message.MessageResp) {
          return mergeFrom((cn.ctodb.push.proto.Message.MessageResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.ctodb.push.proto.Message.MessageResp other) {
        if (other == cn.ctodb.push.proto.Message.MessageResp.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getCc() != 0L) {
          setCc(other.getCc());
        }
        if (other.getTs() != 0L) {
          setTs(other.getTs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.ctodb.push.proto.Message.MessageResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.ctodb.push.proto.Message.MessageResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       * 返回消息id
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * 返回消息id
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回消息id
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long cc_ ;
      /**
       * <pre>
       * 与TextReq对应，用于检查发送状态
       * </pre>
       *
       * <code>int64 cc = 2;</code>
       */
      public long getCc() {
        return cc_;
      }
      /**
       * <pre>
       * 与TextReq对应，用于检查发送状态
       * </pre>
       *
       * <code>int64 cc = 2;</code>
       */
      public Builder setCc(long value) {
        
        cc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 与TextReq对应，用于检查发送状态
       * </pre>
       *
       * <code>int64 cc = 2;</code>
       */
      public Builder clearCc() {
        
        cc_ = 0L;
        onChanged();
        return this;
      }

      private long ts_ ;
      /**
       * <pre>
       * 实际发送成功时间戳
       * </pre>
       *
       * <code>int64 ts = 3;</code>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <pre>
       * 实际发送成功时间戳
       * </pre>
       *
       * <code>int64 ts = 3;</code>
       */
      public Builder setTs(long value) {
        
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 实际发送成功时间戳
       * </pre>
       *
       * <code>int64 ts = 3;</code>
       */
      public Builder clearTs() {
        
        ts_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.ctodb.push.proto.MessageResp)
    }

    // @@protoc_insertion_point(class_scope:cn.ctodb.push.proto.MessageResp)
    private static final cn.ctodb.push.proto.Message.MessageResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.ctodb.push.proto.Message.MessageResp();
    }

    public static cn.ctodb.push.proto.Message.MessageResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageResp>
        PARSER = new com.google.protobuf.AbstractParser<MessageResp>() {
      @java.lang.Override
      public MessageResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.ctodb.push.proto.Message.MessageResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TextReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.ctodb.push.proto.TextReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 基本信息
     * </pre>
     *
     * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
     */
    boolean hasBaseInfo();
    /**
     * <pre>
     * 基本信息
     * </pre>
     *
     * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
     */
    cn.ctodb.push.proto.Message.BaseInfo getBaseInfo();
    /**
     * <pre>
     * 基本信息
     * </pre>
     *
     * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
     */
    cn.ctodb.push.proto.Message.BaseInfoOrBuilder getBaseInfoOrBuilder();

    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code cn.ctodb.push.proto.TextReq}
   */
  public  static final class TextReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.ctodb.push.proto.TextReq)
      TextReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextReq.newBuilder() to construct.
    private TextReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextReq() {
      content_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TextReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cn.ctodb.push.proto.Message.BaseInfo.Builder subBuilder = null;
              if (baseInfo_ != null) {
                subBuilder = baseInfo_.toBuilder();
              }
              baseInfo_ = input.readMessage(cn.ctodb.push.proto.Message.BaseInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseInfo_);
                baseInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_TextReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_TextReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ctodb.push.proto.Message.TextReq.class, cn.ctodb.push.proto.Message.TextReq.Builder.class);
    }

    public static final int BASEINFO_FIELD_NUMBER = 1;
    private cn.ctodb.push.proto.Message.BaseInfo baseInfo_;
    /**
     * <pre>
     * 基本信息
     * </pre>
     *
     * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
     */
    public boolean hasBaseInfo() {
      return baseInfo_ != null;
    }
    /**
     * <pre>
     * 基本信息
     * </pre>
     *
     * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
     */
    public cn.ctodb.push.proto.Message.BaseInfo getBaseInfo() {
      return baseInfo_ == null ? cn.ctodb.push.proto.Message.BaseInfo.getDefaultInstance() : baseInfo_;
    }
    /**
     * <pre>
     * 基本信息
     * </pre>
     *
     * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
     */
    public cn.ctodb.push.proto.Message.BaseInfoOrBuilder getBaseInfoOrBuilder() {
      return getBaseInfo();
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseInfo_ != null) {
        output.writeMessage(1, getBaseInfo());
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseInfo());
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.ctodb.push.proto.Message.TextReq)) {
        return super.equals(obj);
      }
      cn.ctodb.push.proto.Message.TextReq other = (cn.ctodb.push.proto.Message.TextReq) obj;

      boolean result = true;
      result = result && (hasBaseInfo() == other.hasBaseInfo());
      if (hasBaseInfo()) {
        result = result && getBaseInfo()
            .equals(other.getBaseInfo());
      }
      result = result && getContent()
          .equals(other.getContent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseInfo()) {
        hash = (37 * hash) + BASEINFO_FIELD_NUMBER;
        hash = (53 * hash) + getBaseInfo().hashCode();
      }
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.ctodb.push.proto.Message.TextReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ctodb.push.proto.Message.TextReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.TextReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ctodb.push.proto.Message.TextReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.TextReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ctodb.push.proto.Message.TextReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.TextReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ctodb.push.proto.Message.TextReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.TextReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.ctodb.push.proto.Message.TextReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ctodb.push.proto.Message.TextReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ctodb.push.proto.Message.TextReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.ctodb.push.proto.Message.TextReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.ctodb.push.proto.TextReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.ctodb.push.proto.TextReq)
        cn.ctodb.push.proto.Message.TextReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_TextReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_TextReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.ctodb.push.proto.Message.TextReq.class, cn.ctodb.push.proto.Message.TextReq.Builder.class);
      }

      // Construct using cn.ctodb.push.proto.Message.TextReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (baseInfoBuilder_ == null) {
          baseInfo_ = null;
        } else {
          baseInfo_ = null;
          baseInfoBuilder_ = null;
        }
        content_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.ctodb.push.proto.Message.internal_static_cn_ctodb_push_proto_TextReq_descriptor;
      }

      @java.lang.Override
      public cn.ctodb.push.proto.Message.TextReq getDefaultInstanceForType() {
        return cn.ctodb.push.proto.Message.TextReq.getDefaultInstance();
      }

      @java.lang.Override
      public cn.ctodb.push.proto.Message.TextReq build() {
        cn.ctodb.push.proto.Message.TextReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.ctodb.push.proto.Message.TextReq buildPartial() {
        cn.ctodb.push.proto.Message.TextReq result = new cn.ctodb.push.proto.Message.TextReq(this);
        if (baseInfoBuilder_ == null) {
          result.baseInfo_ = baseInfo_;
        } else {
          result.baseInfo_ = baseInfoBuilder_.build();
        }
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.ctodb.push.proto.Message.TextReq) {
          return mergeFrom((cn.ctodb.push.proto.Message.TextReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.ctodb.push.proto.Message.TextReq other) {
        if (other == cn.ctodb.push.proto.Message.TextReq.getDefaultInstance()) return this;
        if (other.hasBaseInfo()) {
          mergeBaseInfo(other.getBaseInfo());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.ctodb.push.proto.Message.TextReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.ctodb.push.proto.Message.TextReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cn.ctodb.push.proto.Message.BaseInfo baseInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.ctodb.push.proto.Message.BaseInfo, cn.ctodb.push.proto.Message.BaseInfo.Builder, cn.ctodb.push.proto.Message.BaseInfoOrBuilder> baseInfoBuilder_;
      /**
       * <pre>
       * 基本信息
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
       */
      public boolean hasBaseInfo() {
        return baseInfoBuilder_ != null || baseInfo_ != null;
      }
      /**
       * <pre>
       * 基本信息
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
       */
      public cn.ctodb.push.proto.Message.BaseInfo getBaseInfo() {
        if (baseInfoBuilder_ == null) {
          return baseInfo_ == null ? cn.ctodb.push.proto.Message.BaseInfo.getDefaultInstance() : baseInfo_;
        } else {
          return baseInfoBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 基本信息
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
       */
      public Builder setBaseInfo(cn.ctodb.push.proto.Message.BaseInfo value) {
        if (baseInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseInfo_ = value;
          onChanged();
        } else {
          baseInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 基本信息
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
       */
      public Builder setBaseInfo(
          cn.ctodb.push.proto.Message.BaseInfo.Builder builderForValue) {
        if (baseInfoBuilder_ == null) {
          baseInfo_ = builderForValue.build();
          onChanged();
        } else {
          baseInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 基本信息
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
       */
      public Builder mergeBaseInfo(cn.ctodb.push.proto.Message.BaseInfo value) {
        if (baseInfoBuilder_ == null) {
          if (baseInfo_ != null) {
            baseInfo_ =
              cn.ctodb.push.proto.Message.BaseInfo.newBuilder(baseInfo_).mergeFrom(value).buildPartial();
          } else {
            baseInfo_ = value;
          }
          onChanged();
        } else {
          baseInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 基本信息
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
       */
      public Builder clearBaseInfo() {
        if (baseInfoBuilder_ == null) {
          baseInfo_ = null;
          onChanged();
        } else {
          baseInfo_ = null;
          baseInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 基本信息
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
       */
      public cn.ctodb.push.proto.Message.BaseInfo.Builder getBaseInfoBuilder() {
        
        onChanged();
        return getBaseInfoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 基本信息
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
       */
      public cn.ctodb.push.proto.Message.BaseInfoOrBuilder getBaseInfoOrBuilder() {
        if (baseInfoBuilder_ != null) {
          return baseInfoBuilder_.getMessageOrBuilder();
        } else {
          return baseInfo_ == null ?
              cn.ctodb.push.proto.Message.BaseInfo.getDefaultInstance() : baseInfo_;
        }
      }
      /**
       * <pre>
       * 基本信息
       * </pre>
       *
       * <code>.cn.ctodb.push.proto.BaseInfo baseInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.ctodb.push.proto.Message.BaseInfo, cn.ctodb.push.proto.Message.BaseInfo.Builder, cn.ctodb.push.proto.Message.BaseInfoOrBuilder> 
          getBaseInfoFieldBuilder() {
        if (baseInfoBuilder_ == null) {
          baseInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.ctodb.push.proto.Message.BaseInfo, cn.ctodb.push.proto.Message.BaseInfo.Builder, cn.ctodb.push.proto.Message.BaseInfoOrBuilder>(
                  getBaseInfo(),
                  getParentForChildren(),
                  isClean());
          baseInfo_ = null;
        }
        return baseInfoBuilder_;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.ctodb.push.proto.TextReq)
    }

    // @@protoc_insertion_point(class_scope:cn.ctodb.push.proto.TextReq)
    private static final cn.ctodb.push.proto.Message.TextReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.ctodb.push.proto.Message.TextReq();
    }

    public static cn.ctodb.push.proto.Message.TextReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextReq>
        PARSER = new com.google.protobuf.AbstractParser<TextReq>() {
      @java.lang.Override
      public TextReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TextReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TextReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.ctodb.push.proto.Message.TextReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ctodb_push_proto_BaseInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ctodb_push_proto_BaseInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ctodb_push_proto_MessageResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ctodb_push_proto_MessageResp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ctodb_push_proto_TextReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ctodb_push_proto_TextReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\023cn.ctodb.push.proto\"]\n\010" +
      "BaseInfo\022\014\n\004from\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022+\n\006to" +
      "Type\030\003 \001(\0162\033.cn.ctodb.push.proto.ToType\022" +
      "\n\n\002cc\030\004 \001(\003\"1\n\013MessageResp\022\n\n\002id\030\001 \001(\003\022\n" +
      "\n\002cc\030\002 \001(\003\022\n\n\002ts\030\003 \001(\003\"K\n\007TextReq\022/\n\010bas" +
      "eInfo\030\001 \001(\0132\035.cn.ctodb.push.proto.BaseIn" +
      "fo\022\017\n\007content\030\002 \001(\t*\035\n\006ToType\022\010\n\004USER\020\000\022" +
      "\t\n\005GROUP\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_ctodb_push_proto_BaseInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_ctodb_push_proto_BaseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ctodb_push_proto_BaseInfo_descriptor,
        new java.lang.String[] { "From", "To", "ToType", "Cc", });
    internal_static_cn_ctodb_push_proto_MessageResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_ctodb_push_proto_MessageResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ctodb_push_proto_MessageResp_descriptor,
        new java.lang.String[] { "Id", "Cc", "Ts", });
    internal_static_cn_ctodb_push_proto_TextReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_ctodb_push_proto_TextReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ctodb_push_proto_TextReq_descriptor,
        new java.lang.String[] { "BaseInfo", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
