spring:
    hazelcast: null
    kafka: null
    redis:
        # 单服务配置
        host: server.ctodb.cn
        port: 6379
#        password: 123456
#        pool:
#            maxIdle: 8
#            minIdle: 0
#            maxActive: 8
#            maxWait: -1
# 哨兵模式配置
#        sentinel:
#            master: mymaster
#            nodes: server.ctodb.cn:6379

application:
    server:
        port: 9901 # 默认端口 9901