spring:
    hazelcast: null
    kafka:
        producer:
            bootstrap-servers:
              - server.ctodb.cn:9092
            retries: 0
            batch-size: 16384
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            bootstrap-servers:
              - server.ctodb.cn:9092
            group-id: foo
            auto-offset-reset: earliest
            enable-auto-commit: true
            auto-commit-interval: 100
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    redis:
        password: 123456
        pool:
            maxIdle: 8
            minIdle: 0
            maxActive: 8
            maxWait: -1
        # 单服务配置
        host: 10.16.51.2
        port: 6379
        # 哨兵模式配置
#        sentinel:
#            master: mymaster
#            nodes:

application:
    server:
        port: -1 # 默认端口 9901
        center: http://localhost:8080